### ISSUE TITLE
Orientation of assembling machines with liquid inputs is not preserved after importing a blueprint

### ISSUE THREAD

**Issue by elswindle** [redruin1/factorio-draftsman#32]
When loading an `AssemblingMachine` entity (oil refinery, assembling machine, etc.), the `direction` parameter is not stored and is part of the `unused_args` of the entity.  This is a simple fix, just check for `direction` in the `kwargs` inside the constructor.

**Comment by redruin1** [comment]
This is now fixed. `AssemblingMachine` now inherits `DirectionalMixin`, so you can also specify it's direction from Draftsman as well. Currently there's no logic to check if such a direction attribute is redundant (technically it's only needed in `AssemblingMachine` if it has a fluid recipe), but that has almost zero end-user impact so I will promptly ignore it for now.

Currently I'm hard at work with the entity merging code, and I'm also working on finishing/adding a number of other quality of life features. Due to the scale of the changes (and the fact that some of them are breaking) the next version will most likely be `1.0.0`. I'll probably post an Announcement in the discussion tab detailing all the changes, as cramming them into a changelog seems like a poor idea.
