### ISSUE TITLE
Control behavior schema missing entries

### ISSUE THREAD

**Issue by elswindle** [redruin1/factorio-draftsman#38]
Inserter is missing "circuit_mode_of_operation"
Lamp is missing "circuit_condition"

Lamp may also be missing "circuit_enable_disable", but it is working for me without it.  The whole circuit behavior Schema isn't 100% clear to me yet, so I'm not sure if it is required.

**Comment by redruin1** [comment]
Fixed `circuit_mode_of_operation` and `circuit_condition` in `1.0.1`.

Lamp is unique in that it does not need `circuit_enable_disable`; I remember specifically because this required me to split `CirrcuitConditionMixin` into two separate mixins *just* for this one entity. The UI has a toggle for it, but it is permanently enabled, implying that it was either a vestigial mechanic cut for simplicity, or it's a side effect of using the same control behavior code as everything else and just having the unused parameter.
